<?php

namespace DanieleMontecchi\LaravelBasics\Configurables;

use Illuminate\Support\Facades\URL;
use DanieleMontecchi\LaravelBasics\Contracts\Configurable;

/**
 * Forces all URLs generated by the application to use the HTTPS scheme.
 *
 * This is useful when the application is behind a proxy or CDN
 * that terminates SSL, but Laravel still sees HTTP internally.
 */
class ForceHttpsScheme extends Configurable
{
    public function apply(): void
    {
        URL::forceHttps();
    }
}
